trying to fix error output

diff --git a/.github/workflows/dockerimage.yml b/.github/workflows/dockerimage.yml
--- a/.github/workflows/dockerimage.yml
+++ b/.github/workflows/dockerimage.yml
@@ -132,4 +132,4 @@ jobs:
           echo '===================================================='
         done < folder-list/folders.txt
     - run: |
-        [ -e "errors.txt" ] && echo "ERRORS!!!" && cat errors.txt 
+        [ -e "errors.txt" ] && (echo "ERRORS!" && cat errors.txt) || true
